export const SET_USER_INPUT = 'SET_USER_INPUT';
export const ADD_USER_DATA = 'ADD_USER_DATA';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';

export default {
  SET_USER_INPUT,
  ADD_USER_DATA,
  DELETE_USER_DATA
};
